# Generated by Django 4.0.2 on 2022-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
