# Generated by Django 4.0.2 on 2022-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_category_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=13)),
                ('id_card', models.FileField(upload_to='')),
                ('sem', models.IntegerField()),
                ('roll_no', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
