# Generated by Django 4.0.2 on 2022-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
