# Generated by Django 4.0.2 on 2022-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_category_options_students_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
