# Generated by Django 4.0.2 on 2022-03-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_students_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
